import time
import random
import os

os.system('clear')
print("GAYDAR 9.6.0")
print("YOU ARE USING THE LATEST VERSION OF GAYDAR!")
print()
print("ACTIVATING GAYDAR")
print(".....")
print()
time.sleep(3)
print("GAYDAR ACTIVATED")
print("SCANNING FOR TARGETS")
print(".....")
print()
time.sleep(3)
print(random.randint(100, 1000), "POSSIBLE TARGETS FOUND")
print()

while True:
  name = input("ENTER TARGET NAME: ")
  confirm = input(f"ARE YOU SURE YOU WANT TO TARGET {name}? (y/n): ")
  print()

  if confirm.lower() == "Y":
    print("TARGET LOCKED")
    break
  if confirm.lower() == "y":
   print("TARGET LOCKED")
   break
  else:
   print("TARGET LOCK FAILURE, TRY AGAIN")

print(".....")
print("BAKING A CAKE")
print()
time.sleep(0.5)
print("FINDING FRIEND GROUPS")
time.sleep(1)
print("ERROR: RESULT CAN NOT BE 0")
print()
time.sleep(0.5)
print("TAKING HAPPY PILLS")
print()
time.sleep(0.5)
print("LEGALIZING NUKEULAR BOMBS")
time.sleep(0.5)
print()
print("HACKING THE MAINFRAME")
print()
time.sleep(0.5)
print("FIGHTING SIXTH GRADERS")
print()
time.sleep(0.5)
print("FINDING FATHER")
time.sleep(1)
print("ERROR: CAN NOT FIND SOMETHING THAT DOES NOT EXIST")
print()
time.sleep(0.5)
print("HAVING EXISTENTIAL CRISIS")
print()
time.sleep(0.5)
print("FINISHING WHAT BIN LADEN STARTED")
print()
time.sleep(0.5)
print("CHECKING SEARCH HISTORY")
print()
time.sleep(0.5)
print("PROCRASTINATING")
print()
time.sleep(0.5)
print("PREPARING FOR TITANFALL")
print()
time.sleep(0.5)
print("DOUBLE CHECKING THE LIST")
print()
time.sleep(0.5)
print("LISTENING TO THE CHIKI'S CHASE SOUNDTRACK ON REPEAT")
print()
time.sleep(0.5)
print("ASKING ALEXA TO PLAY DESPACITO")
print(".....")
print()
time.sleep(1)
print("SCAN COMPLETE")
print("WARNING: TURBO ENABLED. CUTTING CORNERS,"
      " FINAL RESULT MAY BE INACCURATE")
print("CALCULTING RESULTS. ETA: 10 SECONDS")
print(".....")
time.sleep(5)
print("PREFORMING FINAL CALCULATIONS")
print(".....")
time.sleep(5)
print("RESULTS CALCULATED")
print(name, "IS", random.randint(0, 100),  "%", "GAY")